server {
    listen 8080;

    root ./www;
    index index.html;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 500 /errors/500.html;
}

server {
    listen 8181;

    root ./www;
    index index.html;

    error_page 400 /errors/500.html;
    error_page 404 /errors/403.html;
    error_page 403 /errors/404.html;
    error_page 500 /errors/400.html;
}