# comentario no tokenizable
server	 
{
	index "hola";
	index hola;
	index 'hola';

	index "\"hola\"";
	index '\'hola\'';
	index "{hola}";

	listen 44.4.4.4:6 ;
	root "./www{patata}'\"";
	error_page 400 /errors/400.html;
	client_max_body_size 100000000000000000k;
}